### ISSUE TITLE
[教育訓練] 參考手冊實際操作 TWCC

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#10]
### To-do:

- 請參考以下三份手冊，按照優先順序，實際操作、了解 TWCC 服務的資訊 👀
- 閱讀完 or 操作完的手冊的請在下方 ✅ 
- 未列入的手冊，以下操作完再參考即可~
- 本週看不完沒關係 🙆 
- 如果有發現文件 bug，請回報在 issue (請附上文件 link、說明、截圖)，謝謝! 🐞 
-  ❓ 不太懂的部分歡迎到 Slack 發問
-  ❗ **特別注意!! 兩位在維運計畫中的身份是租戶管理員，<ins>TWCC 上請小心操作，勿刪除或調整其他成員的資源</ins>** ❗ 
- ❗ **特別注意!! 避免影響其他成員的虛擬運算個體，建立基礎虛擬防火牆，請先另建虛擬網路，勿選用已建立的** ❗ 

### Docs:

<details><summary>1. <a href="https://man.twcc.ai/@twccdocs/doc-service-main-zh">TWCC 會員/計畫/帳務</a> (點開優先順序)</summary>

- 使用指南：
    1. 註冊帳號
    2. 進入會員系統
    3. 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. API 金鑰
    5. 資源配額管理
    6. 管理計畫成員
    7. 檢視計畫資訊
    8. 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. FAQ (會員計畫與帳務/產品概觀/使用者網站) 
 </details>

<details><summary>2. <a href="https://man.twcc.ai/@twccdocs/doc-ccs-main-zh">開發型容器</a> (點開優先順序)</summary>

- 使用指南：
    1. 服務概觀
    2. 建立、連線、管理、監控容器
    3. 高速檔案系統
    4. 雲端物件儲存
    5. 連接埠
    6. 複本

- 案例教學：
    1. 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. 檢視運算資源概況－GPU Burn Testing
    4. 設定開發型容器的服務埠
    5. 自動完成運算及刪除容器
    6. 部署自動化 AI/ML pipeline
    7. Python 套件安裝指南

- 其他資訊：
    1. FAQ (CCS)
    2. 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.ai/@twccdocs/doc-vcs-main-zh">虛擬運算服務</a> (點開優先順序)</summary>

- 使用指南：
  1. 服務概觀
  2. 建立虛擬運算個體
  3. 建立與管理鑰匙對
  4. 準備工作
  5. 連線至 Linux 個體
  6. 連線至 Windows 個體
  7. 檢視/編輯
  8. 停止/啟動/關機/重開機/刪除
  9. 監控
  10. (備份個體)建立映像檔
  11. 建立映像檔最佳作法
  12. 管理映像檔
  13. 建立客製化個體
  14. 建立資料磁碟
  15. 檢視/連結/刪除 資料磁碟
  16. 分離資料磁碟
  17. 備份磁碟
  18. 負載平衡
  19. Auto Scaling
  20. 安全性群組
        
- 案例教學
  1. 初始化磁碟- Linux
  2. 初始化磁碟- Windows
  3. 架設安全、可負載高流量的網站
  4. 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. 個體生命週期

- 其他資訊
  1. FAQ (VCS)
  2. 價目表 (VCS) 
</details>

**Comment by VigaWei** [comment]
## ✅ For XXX (實際操作完的文件請打勾) :

<details><summary>1. <a href="https://man.twcc.ai/@twccdocs/doc-service-main-zh">TWCC 會員/計畫/帳務</a></summary>

- 使用指南：
    1. [ ] 註冊帳號
    2. [ ] 進入會員系統
    3. [ ] 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. [ ] API 金鑰
    5. [ ] 資源配額管理
    6. [ ] 管理計畫成員
    7. [ ] 檢視計畫資訊
    8. [ ] 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. [ ] FAQ (會員計畫與帳務/產品概觀/使用者網站)  
 </details>
 
<details><summary>2. <a href="https://man.twcc.ai/@twccdocs/doc-ccs-main-zh">開發型容器</a></summary>

- 使用指南：
    1. [ ] 服務概觀
    2. [ ] 建立、連線、管理、監控容器
    3. [ ] 高速檔案系統
    4. [ ] 雲端物件儲存
    5. [ ] 連接埠
    6. [ ] 複本

- 案例教學：
    1. [ ] 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. [ ] 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. [ ] 檢視運算資源概況－GPU Burn Testing
    4. [ ] 設定開發型容器的服務埠
    5. [ ] 自動完成運算及刪除容器
    6. [ ] 部署自動化 AI/ML pipeline
    7. [ ] Python 套件安裝指南

- 其他資訊：
    1. [ ] FAQ (CCS)
    2. [ ] 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.ai/@twccdocs/doc-vcs-main-zh">虛擬運算服務</a></summary>

- 使用指南：
  1. [ ] 服務概觀
  2. [ ] 建立虛擬運算個體
  3. [ ] 建立與管理鑰匙對
  4. [ ] 準備工作
  5. [ ] 連線至 Linux 個體
  6. [ ] 連線至 Windows 個體
  7. [ ] 檢視/編輯
  8. [ ] 停止/啟動/關機/重開機/刪除
  9. [ ] 監控
  10. [ ] (備份個體)建立映像檔
  11. [ ] 建立映像檔最佳作法
  12. [ ] 管理映像檔
  13. [ ] 建立客製化個體
  14. [ ] 建立資料磁碟
  15. [ ] 檢視/連結/刪除 資料磁碟
  16. [ ] 分離資料磁碟
  17. [ ] 備份磁碟
  18. [ ] 負載平衡
  19. [ ] Auto Scaling
  20. [ ] 安全性群組
        
- 案例教學
  1. [ ] 初始化磁碟- Linux
  2. [ ] 初始化磁碟- Windows
  3. [ ] 架設安全、可負載高流量的網站
  4. [ ] 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. [ ] 個體生命週期

- 其他資訊
  1. [ ] FAQ (VCS)
  2. [ ] 價目表 (VCS) 

</details>

**Comment by VigaWei** [comment]
## ✅ For XXX (實際操作完的文件請打勾) :

<details><summary>1. <a href="https://man.twcc.ai/@twccdocs/doc-service-main-zh">TWCC 會員/計畫/帳務</a></summary>

- 使用指南：
    1. [ ] 註冊帳號
    2. [ ] 進入會員系統
    3. [ ] 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. [ ] API 金鑰
    5. [ ] 資源配額管理
    6. [ ] 管理計畫成員
    7. [ ] 檢視計畫資訊
    8. [ ] 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. [ ] FAQ (會員計畫與帳務/產品概觀/使用者網站)  
 </details>
 
<details><summary>2. <a href="https://man.twcc.ai/@twccdocs/doc-ccs-main-zh">開發型容器</a></summary>

- 使用指南：
    1. [ ] 服務概觀
    2. [ ] 建立、連線、管理、監控容器
    3. [ ] 高速檔案系統
    4. [ ] 雲端物件儲存
    5. [ ] 連接埠
    6. [ ] 複本

- 案例教學：
    1. [ ] 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. [ ] 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. [ ] 檢視運算資源概況－GPU Burn Testing
    4. [ ] 設定開發型容器的服務埠
    5. [ ] 自動完成運算及刪除容器
    6. [ ] 部署自動化 AI/ML pipeline
    7. [ ] Python 套件安裝指南

- 其他資訊：
    1. [ ] FAQ (CCS)
    2. [ ] 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.ai/@twccdocs/doc-vcs-main-zh">虛擬運算服務</a></summary>

- 使用指南：
  1. [ ] 服務概觀
  2. [ ] 建立虛擬運算個體
  3. [ ] 建立與管理鑰匙對
  4. [ ] 準備工作
  5. [ ] 連線至 Linux 個體
  6. [ ] 連線至 Windows 個體
  7. [ ] 檢視/編輯
  8. [ ] 停止/啟動/關機/重開機/刪除
  9. [ ] 監控
  10. [ ] (備份個體)建立映像檔
  11. [ ] 建立映像檔最佳作法
  12. [ ] 管理映像檔
  13. [ ] 建立客製化個體
  14. [ ] 建立資料磁碟
  15. [ ] 檢視/連結/刪除 資料磁碟
  16. [ ] 分離資料磁碟
  17. [ ] 備份磁碟
  18. [ ] 負載平衡
  19. [ ] Auto Scaling
  20. [ ] 安全性群組
        
- 案例教學
  1. [ ] 初始化磁碟- Linux
  2. [ ] 初始化磁碟- Windows
  3. [ ] 架設安全、可負載高流量的網站
  4. [ ] 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. [ ] 個體生命週期

- 其他資訊
  1. [ ] FAQ (VCS)
  2. [ ] 價目表 (VCS) 

</details>

**Comment by chuchun211** [comment]
**檢視計畫資訊 Step 2. 查看計畫資訊**
文件link: https://man.twcc.ai/@twccdocs/guide-service-view-project-zh?type=view#Step-2-%E6%9F%A5%E7%9C%8B%E8%A8%88%E7%95%AB%E8%B3%87%E8%A8%8A
不算bug只是圖片和實際有出入
附圖的額度看起來是之前的樣式
![image](https://user-images.githubusercontent.com/67446293/179387616-c68af677-898f-434c-9716-f640a1342fcb.png)
我看見的計劃資訊畫面
![image](https://user-images.githubusercontent.com/67446293/179387630-27fcbc1b-4e1a-4587-81e5-ae304c48338a.png)

**Comment by VigaWei** [comment]
> **檢視計畫資訊 Step 2. 查看計畫資訊** 文件link: https://man.twcc.ai/@twccdocs/guide-service-view-project-zh?type=view#Step-2-%E6%9F%A5%E7%9C%8B%E8%A8%88%E7%95%AB%E8%B3%87%E8%A8%8A 不算bug只是圖片和實際有出入 附圖的額度看起來是之前的樣式 ![image](https://user-images.githubusercontent.com/67446293/179387616-c68af677-898f-434c-9716-f640a1342fcb.png) 我看見的計劃資訊畫面 ![image](https://user-images.githubusercontent.com/67446293/179387630-27fcbc1b-4e1a-4587-81e5-ae304c48338a.png)

感謝! 已有排入 8/5 上版項目：https://git.twcc.ai/twcc/manual/-/issues/285

**Comment by chuchun211** [comment]
**註冊 TWCC 帳號**

[註冊 TWCC 帳號 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-service-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-service-signup-zh#%E8%A8%BB%E5%86%8A-TWCC-%E5%B8%B3%E8%99%9F)

依上方連結的Step 1指示按下註冊後
有時候和文件中的Step 2一樣是閱讀個資及權利義務聲明
有時候會跳出[註冊 TWS / TWCC 帳號 - HackMD (twcc.ai)](https://man.twcc.ai/@twsdocs/doc-mber-pjct-blng-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twsdocs%2Fguide-service-signup-zh)中的Step 2. 輸入註冊帳號的信箱
但是頁面是iService而非TWS
![image](https://user-images.githubusercontent.com/67446293/179655910-c7eb5673-15b5-4fd6-b741-8906dcf4d9fd.png)

不知是否有無影響

**Comment by chuchun211** [comment]
[使用 TensorFlow 訓練 MNIST 手寫數字辨識模型 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2FryoveCipN%3Ftype%3Dview#Step-3-%E9%80%A3%E7%B7%9A%E5%AE%B9%E5%99%A8%E3%80%81%E4%B8%8B%E8%BC%89%E8%A8%93%E7%B7%B4%E7%A8%8B%E5%BC%8F)
 
![image](https://user-images.githubusercontent.com/67446293/179667770-8a2ae24f-a46d-4e5f-a41a-d41ba53b1adc.png)

「使用Jupyter Notebook」的連結點下去會是開發型容器的服務概觀
或許改到[連線容器 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-connect-zh)會更直覺

**Comment by Oysteranpu** [comment]
[管理容器-刪除容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-manage-zh#%E5%88%AA%E9%99%A4%E5%AE%B9%E5%99%A8)
刪除容器偶爾發生無法刪除的狀況
可能與啟用或關閉「刪除保護機制」延遲有關
通常稍等一下重新整理即可解決
![image](https://user-images.githubusercontent.com/109254397/179673413-2bef3455-0fb7-4e0e-929b-55347be9d43b.png)

**Comment by chuchun211** [comment]
[管理專案成員 - HackMD (twcc.ai)](https://man.twcc.ai/@twsdocs/doc-mber-pjct-blng-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twsdocs%2Fguide-service-manage-project-team-zh)
TWS的說明文字和圖片中的「計畫」
在實際操作時都是「專案」
![image](https://user-images.githubusercontent.com/67446293/179688913-a8f24f23-80c5-4584-81c6-73da5b401ab0.png)

**Comment by Oysteranpu** [comment]
[雲端物件儲存-建立刪除儲存體](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-create-delete-bucket-zh)
HackMD目前的圖如下：
![image](https://user-images.githubusercontent.com/109254397/179721718-d4879cbb-29a6-49e6-9d53-fcac991700bd.png)

實際操作左側列表稍有不同：
![image](https://user-images.githubusercontent.com/109254397/179722611-7b4194bc-12f6-4b8b-9657-e7bd35808f41.png)

**Comment by Oysteranpu** [comment]
[雲端物件儲存-檢視、搜尋、刪除檔案](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-view-search-delete-files-zh)
在搜尋檔案的部分HackMD中的圖有"進階METADATA搜尋"
![image](https://user-images.githubusercontent.com/109254397/179724218-726eaaf6-82f0-4f87-b2f4-d426d945e9f2.png)

實際操作則沒有(用的是租戶使用者的帳號，不知是否有影響)
![image](https://user-images.githubusercontent.com/109254397/179725193-5a7fed8c-99fd-42d9-999c-2d140b47aa13.png)

**Comment by chuchun211** [comment]
[TWCC FAQs 容器運算服務 連線登入](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-ccs-zh#%E9%80%A3%E7%B7%9A%E7%99%BB%E5%85%A5)
![image](https://user-images.githubusercontent.com/67446293/179967056-54874c50-c415-42e7-a32f-8fa7ffb94eb4.png)
上圖的連線容器會連結到開發型容器的服務概觀
改成[連線容器 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-connect-zh)或許更直覺？

-------------------------------------------------------------------

[TWCC FAQs 容器運算服務 資源配置與監控](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-ccs-zh#%E8%B3%87%E6%BA%90%E9%85%8D%E7%BD%AE%E8%88%87%E7%9B%A3%E6%8E%A7)

![image](https://user-images.githubusercontent.com/67446293/179968082-dd8aa0e1-6fd1-4c0c-9091-8272a416a65e.png)
上圖的連線容器會連結到開發型容器的服務概觀
改成[監控容器 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-ccs-monitor-zh)或許更直覺？

**Comment by chuchun211** [comment]
[停止/啟動/關機/重開機/刪除 - HackMD (twcc.ai)](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-manage-instance-zh#%E5%81%9C%E6%AD%A2%E5%80%8B%E9%AB%94)

停止和啟動的示範截圖上沒有重開機的按鈕
![image](https://user-images.githubusercontent.com/67446293/180107878-7ea8d88c-f758-4d79-b67b-b563d40a9cc0.png)
![image](https://user-images.githubusercontent.com/67446293/180107884-1824fdb7-efec-433d-bbed-1e4a1307e5b4.png)

實際介面
![image](https://user-images.githubusercontent.com/67446293/180107897-51797ed9-7abd-4609-8b7e-33d921572b52.png)

**Comment by VigaWei** [comment]
請 @chuchun211 @Oysteranpu 協助將以上 bug 開成 GitHub issue，之後更新文件工時，可以一併討論更新，感謝! 🙏 

issue name & issue content 請至少需要記錄以下資訊：
- 標題：[待討論] or [待調整] + 文件標題 + 簡略問題描述 `(例：[待調整] 個體生命週期 介面和文件不一致)`
- 內容：
  - 待調整/待討論 文件連結：
  - 目前狀況 (as is)：
  - 理想狀況 (to be)： 

> 開 issue 流程：
> ![create_issue](https://user-images.githubusercontent.com/46370453/180900043-0c60d4e6-22cb-4d0e-88ca-253327b49fd0.gif)

**Comment by VigaWei** [comment]
> > **檢視計畫資訊 Step 2. 查看計畫資訊** 文件link: https://man.twcc.ai/@twccdocs/guide-service-view-project-zh?type=view#Step-2-%E6%9F%A5%E7%9C%8B%E8%A8%88%E7%95%AB%E8%B3%87%E8%A8%8A 不算bug只是圖片和實際有出入 附圖的額度看起來是之前的樣式 ![image](https://user-images.githubusercontent.com/67446293/179387616-c68af677-898f-434c-9716-f640a1342fcb.png) 我看見的計劃資訊畫面 ![image](https://user-images.githubusercontent.com/67446293/179387630-27fcbc1b-4e1a-4587-81e5-ae304c48338a.png)
> 
> 感謝! 已有排入 8/5 上版項目：https://git.twcc.ai/twcc/manual/-/issues/285

這題可以不用開 issue~~ 因為已包含在上版處理項目

**Comment by VigaWei** [comment]
Thank you!
