### ISSUE TITLE
[中文對齊] 開發型容器-2

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#207]
> lang
> - [x] zh-Hant 
> - [ ] En

## Source docs

- zh: https://github.com/twcc/man-vip/issues/26 (檢視 Docusaurus 上的這些文件)
> 遇到還沒 merge 最新的內容，請先拉已開 PR 的檔案複製來改，若後續 merge 有衝突再解

## Target folders and files

如上述，也可直接參考 https://man.twcc.vip 上的內容：
- zh 路徑：`https://man.twcc.vip/` 之後的內容就是檔案路徑

## To-dos

1. 因搬家過程中 HackMD 也有異動，請確認此 issue 是否包含以下文件：
- [x] N 
- [ ] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs
    - [ ] [TWCC 角色權限比較：聯網與資安服務](https://man.twcc.ai/@twccdocs/role-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Frole-netndsec-zh)
    - [ ] [註冊 TWS / TWCC 帳號](https://man.twcc.ai/@twsdocs/guide-service-signup-zh)
    - [ ] [HowTo：進入會員中心？](https://man.twcc.ai/@twsdocs/howto-service-access-service-zh)
    - [ ] [FAQ-產品概觀](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-product-zh)
    - [ ] [FAQ-CFS](https://man.twcc.ai/@twccdocs/faq-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Ffaq-cfs-zh)
    - [ ] [CCS-容器映像檔-Matlab (BYOL)](https://man.twcc.ai/@twccdocs/ccs-concept-image-main-zh/%2F%40twccdocs%2Fccs-concept-image-matlab-zh)
    - [ ] [COS-建立刪除儲存體](https://man.twcc.ai/@twccdocs/doc-cos-main-zh/%2F%40twccdocs%2Fguide-cos-create-delete-bucket-zh)
    - [ ] [VCS-監控個體](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-guide-monitor-instance-zh)
    - [ ] [VCS-彈性 IP](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-vcs-eip-zh)
    - [ ] [HowTo：建立 TWNIA2 容器](https://man.twcc.ai/@twccdocs/doc-twnia2-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-twnia2-create-sglrt-container-zh)

2. 請確認此 issue 是否包含 https://github.com/twcc/man-vip/issues?q=is%3Aissue+is%3Aopen+label%3Aneed-to-update 項目：
- [x] Y，請更新文字、截圖 (連結問題可先略)
- [ ] N 

3. 請按照手冊說明的流程，操作介面，是否發現手冊與介面之間有落差? 或是按照手冊無法操作完成?
- [x] Y，請更新文字、截圖 (連結問題可先略)
- [ ] N 

Note:
- 主要檢視項目：在 UI/CLI 使用流程上，在截圖 & 說明是否已過時或有誤
- 無法按照操作的內容 (描述性的介紹)，可以抓是否有錯字
- 若內容需大幅度的更新，請先通知 Viga 確認
- 連結先不處理
- 建基礎虛擬防火牆請小心，虛擬網路請使用 `vigatrustnetwork` (勿使用 default_network 或其他別人建立的網路)

**Comment by Oysteranpu** [comment]
更新 [設定開發型容器的服務埠-建立容器](https://man.twcc.ai/@twccdocs/howto-ccs-config-service-port-zh#HowTo%EF%BC%9A%E8%A8%AD%E5%AE%9A%E9%96%8B%E7%99%BC%E5%9E%8B%E5%AE%B9%E5%99%A8%E7%9A%84%E6%9C%8D%E5%8B%99%E5%9F%A0)、[確保計算工作能持續不中斷-Step 1&2](https://man.twcc.ai/@twccdocs/howto-ccs-keep-your-processes-running-continuously-zh?type=view#HowTo%EF%BC%9A%E7%A2%BA%E4%BF%9D%E8%A8%88%E7%AE%97%E5%B7%A5%E4%BD%9C%E8%83%BD%E6%8C%81%E7%BA%8C%E4%B8%8D%E4%B8%AD%E6%96%B7)、[開發型容器詳細資料](https://man.twcc.ai/@twccdocs/howto-ccs-tensorflow-inception-v3-port-zh?type=view#HowTo%EF%BC%9A%E4%BD%BF%E7%94%A8-TensorFlow-Inception-V3-%E8%A8%93%E7%B7%B4%E5%BD%B1%E5%83%8F%E8%BE%A8%E8%AD%98%E6%A8%A1%E5%9E%8B%E3%80%81%E7%94%9F%E6%88%90%E6%8E%A8%E8%AB%96%E5%BC%95%E6%93%8E)
共計四處圖片，原因：同 #63 
HackMD目前的圖如下：
![image](https://user-images.githubusercontent.com/109254397/181078003-b0b61c82-3db4-4e1c-acc7-4ce5ea5f4e5f.png)

實際操作左側列表與深入了解的部分稍有不同
![image](https://user-images.githubusercontent.com/109254397/181077376-8b8e802c-e97e-4b14-b51e-8a3148dbfdec.png)

**Comment by VigaWei** [comment]
### 4. 以下幾篇文件 HackMD 也有更新，請確認此 issue 是否包含以下文件：

- [ ] N 
- [ ] Y，請將該篇打勾，並檢視 HackMD 最新一筆更新紀錄、更新差異至 Dcsrs  (請在 8/19 後再更新差異)
- [快速入門](https://man.twcc.ai/@twccdocs/By1rH2oaV)
- [任務型容器](https://man.twcc.ai/@twccdocs/doc-ccs-scheduled-main-zh)
- [高速運算任務](https://man.twcc.ai/@twccdocs/doc-hpc-job-main-zh)
- [虛擬運算個體映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-instance-image-zh)
- [管理映像檔](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fvcs-vds-manage-instance-image-zh)
- [HowTo：調整虛擬運算個體規格](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-vcs-resize-instance-zh)
