### ISSUE TITLE
[教育訓練] 參考手冊實際操作 TWCC

### ISSUE THREAD

**Issue by VigaWei** [twcc/man-vip#343]
### To-do:

- 請參考以下三份手冊，按照優先順序，實際操作、了解 TWCC 服務的資訊 👀
- 閱讀完 or 操作完的手冊的請在下方 ✅ 
- 未列入的手冊，以下操作完再參考即可~
- 本週看不完沒關係 🙆 
- 如果有發現文件 bug，請回報在 issue (請附上文件 link、說明、截圖)，謝謝! 🐞 
-  ❓ 不太懂的部分歡迎到 Slack 發問
-  ❗ **特別注意!! 兩位在維運計畫中的身份是租戶管理員，<ins>TWCC 上請小心操作，勿刪除或調整其他成員的資源</ins>** ❗ 
- ❗ **特別注意!! 避免影響其他成員的虛擬運算個體，建立基礎虛擬防火牆，請先另建虛擬網路，勿選用已建立的** ❗ 

### Docs:

<details><summary>1. <a href="https://man.twcc.vip/docs/member/user-guides/member-key-quota/sign-up-for-twcc">TWCC 會員中心</a> (點開優先順序)</summary>

- 使用指南：
    1. 註冊帳號
    2. 進入會員系統
    3. 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. API 金鑰
    5. 資源配額管理
    6. 管理計畫成員
    7. 檢視計畫資訊
    8. 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. FAQ (會員計畫與帳務/產品概觀/使用者網站) 
 </details>

<details><summary>2. <a href="https://man.twcc.vip/docs/ccs-interactive-container/overview">開發型容器</a> (點開優先順序)</summary>

- 使用指南：
    1. 服務概觀
    2. 建立、連線、管理、監控容器
    3. 高速檔案系統
    4. 雲端物件儲存
    5. 連接埠
    6. 複本

- 案例教學：
    1. 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. 檢視運算資源概況－GPU Burn Testing
    4. 設定開發型容器的服務埠
    5. 自動完成運算及刪除容器
    6. 部署自動化 AI/ML pipeline
    7. Python 套件安裝指南

- 其他資訊：
    1. FAQ (CCS)
    2. 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.vip/docs/vcs/overview">虛擬運算服務</a> (點開優先順序)</summary>

- 使用指南：
  1. 服務概觀
  2. 建立虛擬運算個體
  3. 建立與管理鑰匙對
  4. 準備工作
  5. 連線至 Linux 個體
  6. 連線至 Windows 個體
  7. 檢視/編輯
  8. 停止/啟動/關機/重開機/刪除
  9. 監控
  10. (備份個體)建立映像檔
  11. 建立映像檔最佳作法
  12. 管理映像檔
  13. 建立客製化個體
  14. 建立資料磁碟
  15. 檢視/連結/刪除 資料磁碟
  16. 分離資料磁碟
  17. 備份磁碟
  18. 負載平衡
  19. Auto Scaling
  20. 安全性群組
        
- 案例教學
  1. 初始化磁碟- Linux
  2. 初始化磁碟- Windows
  3. 架設安全、可負載高流量的網站
  4. 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. 個體生命週期

- 其他資訊
  1. FAQ (VCS)
  2. 價目表 (VCS) 
</details>

**Comment by VigaWei** [comment]
## ✅ For Jessica (實際操作完的文件請打勾) :

<details><summary>1. <a href="https://man.twcc.ai/@twccdocs/doc-service-main-zh">TWCC 會員/計畫/帳務</a></summary>

- 使用指南：
    1. [ ] 註冊帳號
    2. [ ] 進入會員系統
    3. [ ] 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. [ ] API 金鑰
    5. [ ] 資源配額管理
    6. [ ] 管理計畫成員
    7. [ ] 檢視計畫資訊
    8. [ ] 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. [ ] FAQ (會員計畫與帳務/產品概觀/使用者網站)  
 </details>
 
<details><summary>2. <a href="https://man.twcc.ai/@twccdocs/doc-ccs-main-zh">開發型容器</a></summary>

- 使用指南：
    1. [ ] 服務概觀
    2. [ ] 建立、連線、管理、監控容器
    3. [ ] 高速檔案系統
    4. [ ] 雲端物件儲存
    5. [ ] 連接埠
    6. [ ] 複本

- 案例教學：
    1. [ ] 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. [ ] 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. [ ] 檢視運算資源概況－GPU Burn Testing
    4. [ ] 設定開發型容器的服務埠
    5. [ ] 自動完成運算及刪除容器
    6. [ ] 部署自動化 AI/ML pipeline
    7. [ ] Python 套件安裝指南

- 其他資訊：
    1. [ ] FAQ (CCS)
    2. [ ] 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.ai/@twccdocs/doc-vcs-main-zh">虛擬運算服務</a></summary>

- 使用指南：
  1. [ ] 服務概觀
  2. [ ] 建立虛擬運算個體
  3. [ ] 建立與管理鑰匙對
  4. [ ] 準備工作
  5. [ ] 連線至 Linux 個體
  6. [ ] 連線至 Windows 個體
  7. [ ] 檢視/編輯
  8. [ ] 停止/啟動/關機/重開機/刪除
  9. [ ] 監控
  10. [ ] (備份個體)建立映像檔
  11. [ ] 建立映像檔最佳作法
  12. [ ] 管理映像檔
  13. [ ] 建立客製化個體
  14. [ ] 建立資料磁碟
  15. [ ] 檢視/連結/刪除 資料磁碟
  16. [ ] 分離資料磁碟
  17. [ ] 備份磁碟
  18. [ ] 負載平衡
  19. [ ] Auto Scaling
  20. [ ] 安全性群組
        
- 案例教學
  1. [ ] 初始化磁碟- Linux
  2. [ ] 初始化磁碟- Windows
  3. [ ] 架設安全、可負載高流量的網站
  4. [ ] 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. [ ] 個體生命週期

- 其他資訊
  1. [ ] FAQ (VCS)
  2. [ ] 價目表 (VCS) 

</details>

**Comment by xujshjxkwndmd** [comment]
[開發型容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh) 中的「使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎」沒辦法順利做完，映象檔有照著設定選：
![image](https://user-images.githubusercontent.com/56674698/202343348-11c70ba6-5336-4ab8-9392-f560afb64e6a.png)

在執行 `bash V3_training.sh --path ./cifar-10-python.tar.gz` 時會遇到這個問題：
![image](https://user-images.githubusercontent.com/56674698/202344628-414f6a1c-afaa-41ae-9c24-e91587a7e410.png)

有用過 `pip list --user` 檢查，local 沒有安裝任何套件。
![image](https://user-images.githubusercontent.com/56674698/202345193-3b2289fe-b5cc-4907-9000-31650a7810a1.png)

**Comment by twsc-aug** [comment]
it looks like this tutorial  need to update by engineer >_<
